---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  CacheRootDirectory: "tmp/rubocop_cache"
  Exclude:
    - "bin/bundle"
    - "bin/kamal"
    - "db/*schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/MissingSuper:
  AllowedParentClasses:
    - Result

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - db/seeds.rb
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:
    - app/services/**/*.rb

Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: true
  Exclude:
    - app/controllers/health_controller.rb

RSpec/ExampleLength:
  Max: 20

RSpec/ImplicitSubject:
  EnforcedStyle: single_line_only

RSpec/NestedGroups:
  Max: 4

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - "db/**/*"
    - "spec/**/*"
  RequireForNonPublicMethods: true

Style/ExpandPathArguments:
  Enabled: true
  Exclude:
    - bin/*

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
