services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: miroha
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379

  web:
    build:
      args:
        BUNDLE_WITHOUT: test
        ENVIRONMENT: development
    ports:
      - 3000:3000
    environment:
      BINDING: 0.0.0.0
      DATABASE_URL: postgres://miroha@database:5432/miroha
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
      - redis
