# syntax = devthefuture/dockerfile-x

# Include the application Dockerfile.
INCLUDE ./Dockerfile

# Create an image for the tests.
FROM ruby:$RUBY_VERSION AS tests

# Accept optional arguments.
ARG ENVIRONMENT="development"

# Set environment variables.
ENV NODE_ENV=${ENVIRONMENT} \
  RAILS_ENV=${ENVIRONMENT}

# Install dependency requirements.
RUN apk -U upgrade \
  && apk add --no-cache bash chromium-chromedriver libpq-dev nodejs tzdata yarn

# Create the application directory and set it as the working directory.
RUN mkdir -p /home/runner/application
WORKDIR /home/runner/application

# Copy the assets, dependencies, and application into Docker.
COPY --from=node-builder /build/app/assets/builds app/assets/builds
COPY --from=node-builder /build/node_modules node_modules
COPY --from=ruby-builder /usr/local/bundle /usr/local/bundle
COPY . .

# Precompile the Bootsnap cache.
RUN bundle exec bootsnap precompile --gemfile app/ lib/

# Compile the assets.
RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile
