services:
  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379

  web:
    build:
      args:
        BUNDLE_WITHOUT: test
        ENVIRONMENT: development
    ports:
      - 3000:3000
    environment:
      BINDING: 0.0.0.0
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
