name: Bug Report
description: Create a bug report for Miroha.
labels: ["bug-report"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How To Reproduce
      description: Clearly defined steps to reproduce the behavior. Screenshots can be provided if needed.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear. Anyone should be able to follow the steps provided in order to reproduce the bug. These steps are used to add integration tests to ensure the same issue does not happen again. Thanks!
  - type: input
    attributes:
      label: What browser are you using?
      placeholder: Chrome, Safari, Firefox, etc.
  - type: input
    attributes:
      label: What operating system are you using?
      placeholder: macOS, Windows, Linux, etc.
  - type: input
    attributes:
      label: How are you running Miroha?
      placeholder: Heroku, VPS, locally, etc.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched and there is no existing issue.
        required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tristandunn/miroha/blob/main/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
