---
name: Feature Request
description: Create a feature request for Miroha.
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to file a feature request! Please provide as
        much detail as possible.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature?
      description:
        Please search to see if an issue already exists for the feature you are
        requesting.
      options:
        - label: I have searched and there is no existing issue.
          required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/tristandunn/miroha/blob/main/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
