default: &default
  compile: true
  cache_path: tmp/cache/webpacker
  extract_css: true
  source_path: app/assets
  cache_manifest: false
  resolved_paths: []
  additional_paths: []
  public_root_path: public
  source_entry_path: packs
  public_output_path: packs
  check_yarn_integrity: false
  webpack_compile_output: true

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    watch_options:
      ignored: "**/node_modules/**"

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default

  compile: false
  cache_manifest: true
