---
name: Deploy to Staging

concurrency: staging

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/ci.yml

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: Staging
      url: https://staging.miroha.com

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Staging
        uses: dokku/github-action@v1.5.0
        with:
          branch: staging
          git_push_flags: "--force"
          git_remote_url: ${{ secrets.STAGING_REMOTE }}
          ssh_private_key: ${{ secrets.STAGING_PRIVATE_KEY }}
